version: 2
jobs:
  lint_and_style:
    docker:
      - image: circleci/node: 10.0.0
    steps:
      - checkout
      - run: npm run lint
  test:
    docker:
      - image: circleci/node: 10.0.0
    steps:
      - checkout
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint_and_style
      - test
