version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
  lint_and_style:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: Lint your lib
          command: npm run lint
  test:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: Test your code with AVA
          command: npm test
  test_style:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: Check style with Prettier
          command: npm run style
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint_and_style:
        requires:
            - build
      - test:
        requires:
            - build
      - test_style:
        requires:
            - build
