version: 2
jobs:
  install:
    docker:
      - image: circleci/node10.0.0
    steps:
      - checkout
      - run:
          name: Install npm wee
          command: npm install
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint_and_style:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: Lint your lib
          command: npm run lint
  test:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: Test your code with AVA
          command: npm test
  test_style:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: Check style with Prettier
          command: npm run style
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint_and_style:
          requires:
            - build
      - test:
          requires:
            - build
      - test_style:
          requires:
            - build
